#pragma once
#include <Systems/AnimationSystem.hpp>
#include <Systems/CameraSystem.hpp>
#include <Systems/CollisionDetectionSystem.hpp>
#include <Systems/CollisionResolutionSystem.hpp>
#include <Systems/PlayerEnemyCollisionSystem.hpp>
#include <Systems/PlayerMovementSystem.hpp>
#include <Systems/GravitySystem.hpp>
#include <Systems/LifeSystem.hpp>
#include <Systems/MovementSystem.hpp>
#include <Systems/ControlSystem.hpp>
#include <Systems/PlayerInputSystem.hpp>
#include <Systems/PlayerStateSystem.hpp>
#include <Systems/RenderSystem.hpp>