#pragma once
#include <Systems/AnimationSystem.hpp>
#include <Systems/CameraSystem.hpp>
#include <Systems/ColliderSystem.hpp>
#include <Systems/GravitySystem.hpp>
#include <Systems/MovementSystem.hpp>
#include <Systems/PlayerControlSystem.hpp>
#include <Systems/PlayerInputSystem.hpp>
#include <Systems/RenderSystem.hpp>
#include <Systems/StateSystem.hpp>