#include <StateManager.hpp>

#include <Gameplay/Enemy/Spiny/SpinyNormalBehaviour.hpp>
#include <Gameplay/Enemy/Spiny/SpinyNormalState.hpp>
#include <Gameplay/Enemy/Spiny/SpinyEggState.hpp>
#include <Gameplay/Enemy/Spiny/SpinyEggBehaviour.hpp>
#include <Gameplay/Enemy/Spiny/SpinyFlippedState.hpp>
#include <Gameplay/Enemy/Spiny/SpinyFlippedBehaviour.hpp>
#include <Gameplay/Enemy/Lakitu/LakituFlippedState.hpp>
#include <Gameplay/Enemy/Lakitu/LakituFlippedBehaviour.hpp>
#include <Gameplay/Enemy/Lakitu/LakituNormalBehaviour.hpp>
#include <Gameplay/Enemy/Lakitu/LakituNormalState.hpp>
#include <Gameplay/Enemy/Koopa/KoopaReviveState.hpp>
#include <Gameplay/Enemy/Koopa/KoopaNormalState.hpp>
#include <Gameplay/Enemy/Koopa/KoopaFlippedState.hpp>
#include <Gameplay/Enemy/Koopa/KoopaShell_ReviveBehaviour.hpp>
#include <Gameplay/Enemy/Koopa/KoopaSlideState.hpp>
#include <Gameplay/Enemy/Koopa/KoopaFlippedBehaviour.hpp>
#include <Gameplay/Enemy/Koopa/KoopaJumpingState.hpp>
#include <Gameplay/Enemy/Koopa/KoopaSlideBehaviour.hpp>
#include <Gameplay/Enemy/Koopa/KoopaFlyingState.hpp>
#include <Gameplay/Enemy/Koopa/KoopaNormalBehaviour.hpp>
#include <Gameplay/Enemy/Koopa/KoopaJumpingBehaviour.hpp>
#include <Gameplay/Enemy/Koopa/KoopaFlyingBehaviour.hpp>
#include <Gameplay/Enemy/Koopa/KoopaShellState.hpp>
#include <Gameplay/Enemy/Goomba/GoombaStompedState.hpp>
#include <Gameplay/Enemy/Goomba/GoombaFlippedState.hpp>
#include <Gameplay/Enemy/Goomba/GoombaNormalState.hpp>
#include <Gameplay/Enemy/Goomba/GoombaBehaviour.hpp>
#include <Gameplay/Enemy/Piranha/PiranhaBehaviour.hpp>
#include <Gameplay/Enemy/Piranha/PiranhaNormalState.hpp>
#include <Gameplay/Enemy/Bowser/BowserIdleBehaviour.hpp>
#include <Gameplay/Enemy/Bowser/BowserIdleState.hpp>
#include <Gameplay/Enemy/Bowser/BowserDeadState.hpp>
#include <Gameplay/Enemy/Bowser/BowserHurtState.hpp>
#include <Gameplay/Enemy/Bowser/BowserWalkBehaviour.hpp>
#include <Gameplay/Enemy/Bowser/BowserJumpState.hpp>
#include <Gameplay/Enemy/Bowser/BowserSlideState.hpp>
#include <Gameplay/Enemy/Bowser/BowserWalkState.hpp>
#include <Gameplay/Enemy/Bowser/BowserDeadBehaviour.hpp>
#include <Gameplay/Enemy/Bowser/BowserSlideBehaviour.hpp>
#include <Gameplay/Enemy/Bowser/BowserSkidState.hpp>
#include <Gameplay/Enemy/Bowser/BowserJumpBehaviour.hpp>
#include <Gameplay/Enemy/Bowser/BowserBullet/BowserBulletBehaviour.hpp>
#include <Gameplay/Enemy/Bowser/BowserSkidBehaviour.hpp>
#include <Gameplay/Enemy/Bowser/BowserHurtBehaviour.hpp>
#include <Gameplay/Player/PlayerMovementStates/PlayerJumpingState.hpp>
#include <Gameplay/Player/PlayerMovementStates/PlayerClimbingState.hpp>
#include <Gameplay/Player/PlayerMovementStates/PlayerIdlingState.hpp>
#include <Gameplay/Player/PlayerMovementStates/PlayerRunningState.hpp>
#include <Gameplay/Player/PlayerMovementStates/PlayerCrouchingState.hpp>
#include <Gameplay/Player/PlayerMovementStates/PlayerShootingState.hpp>
#include <Gameplay/Player/PlayerPowerStates/PlayerInvincibleState.hpp>
#include <Gameplay/Player/PlayerPowerStates/PlayerNormalState.hpp>
#include <Gameplay/Player/PlayerSizeStates/PlayerShrinkingState.hpp>
#include <Gameplay/Player/PlayerSizeStates/PlayerFireState.hpp>
#include <Gameplay/Player/PlayerSizeStates/PlayerGrowingUpState.hpp>
#include <Gameplay/Player/PlayerSizeStates/PlayerSmallState.hpp>
#include <Gameplay/Player/PlayerSizeStates/PlayerDeadState.hpp>
#include <Gameplay/Player/PlayerSizeStates/PlayerBigState.hpp>

DEFINE_STATE(EnemyBehaviour, SpinyNormalBehaviour)
DEFINE_STATE(EnemyState, SpinyNormalState)
DEFINE_STATE(EnemyState, SpinyEggState)
DEFINE_STATE(EnemyBehaviour, SpinyEggBehaviour)
DEFINE_STATE(EnemyState, SpinyFlippedState)
DEFINE_STATE(EnemyBehaviour, SpinyFlippedBehaviour)
DEFINE_STATE(EnemyState, LakituFlippedState)
DEFINE_STATE(EnemyBehaviour, LakituFlippedBehaviour)
DEFINE_STATE(EnemyBehaviour, LakituNormalBehaviour)
DEFINE_STATE(EnemyState, LakituNormalState)
DEFINE_STATE(EnemyState, KoopaReviveState)
DEFINE_STATE(EnemyState, KoopaNormalState)
DEFINE_STATE(EnemyState, KoopaFlippedState)
DEFINE_STATE(EnemyBehaviour, KoopaShell_ReviveBehaviour)
DEFINE_STATE(EnemyState, KoopaSlideState)
DEFINE_STATE(EnemyBehaviour, KoopaFlippedBehaviour)
DEFINE_STATE(EnemyState, KoopaJumpingState)
DEFINE_STATE(EnemyBehaviour, KoopaSlideBehaviour)
DEFINE_STATE(EnemyState, KoopaFlyingState)
DEFINE_STATE(EnemyBehaviour, KoopaNormalBehaviour)
DEFINE_STATE(EnemyBehaviour, KoopaJumpingBehaviour)
DEFINE_STATE(EnemyBehaviour, KoopaFlyingBehaviour)
DEFINE_STATE(EnemyState, KoopaShellState)
DEFINE_STATE(EnemyState, GoombaStompedState)
DEFINE_STATE(EnemyState, GoombaFlippedState)
DEFINE_STATE(EnemyState, GoombaNormalState)
DEFINE_STATE(EnemyBehaviour, GoombaBehaviour)
DEFINE_STATE(EnemyBehaviour, PiranhaBehaviour)
DEFINE_STATE(EnemyState, PiranhaNormalState)
DEFINE_STATE(EnemyBehaviour, BowserIdleBehaviour)
DEFINE_STATE(EnemyState, BowserIdleState)
DEFINE_STATE(EnemyState, BowserDeadState)
DEFINE_STATE(EnemyState, BowserHurtState)
DEFINE_STATE(EnemyBehaviour, BowserWalkBehaviour)
DEFINE_STATE(EnemyState, BowserJumpState)
DEFINE_STATE(EnemyState, BowserSlideState)
DEFINE_STATE(EnemyState, BowserWalkState)
DEFINE_STATE(EnemyBehaviour, BowserDeadBehaviour)
DEFINE_STATE(EnemyBehaviour, BowserSlideBehaviour)
DEFINE_STATE(EnemyState, BowserSkidState)
DEFINE_STATE(EnemyBehaviour, BowserJumpBehaviour)
DEFINE_STATE(EnemyBehaviour, BowserBulletBehaviour)
DEFINE_STATE(EnemyBehaviour, BowserSkidBehaviour)
DEFINE_STATE(EnemyBehaviour, BowserHurtBehaviour)
DEFINE_STATE(PlayerMovementState, PlayerJumpingState)
DEFINE_STATE(PlayerMovementState, PlayerClimbingState)
DEFINE_STATE(PlayerMovementState, PlayerIdlingState)
DEFINE_STATE(PlayerMovementState, PlayerRunningState)
DEFINE_STATE(PlayerMovementState, PlayerCrouchingState)
DEFINE_STATE(PlayerMovementState, PlayerShootingState)
DEFINE_STATE(PlayerPowerState, PlayerInvincibleState)
DEFINE_STATE(PlayerPowerState, PlayerNormalState)
DEFINE_STATE(PlayerSizeState, PlayerShrinkingState)
DEFINE_STATE(PlayerSizeState, PlayerFireState)
DEFINE_STATE(PlayerSizeState, PlayerGrowingUpState)
DEFINE_STATE(PlayerSizeState, PlayerSmallState)
DEFINE_STATE(PlayerSizeState, PlayerDeadState)
DEFINE_STATE(PlayerSizeState, PlayerBigState)